use super::unsafe_ref::UnsafeRef;
use crate::chip::chip_lib::core::reference_counted::rc::{Allocator, Rc};
use core::mem::ManuallyDrop;
use core::ops::Deref;
use core::marker::PhantomData;
use core::ptr::NonNull;
use core::cell::Cell;

pub trait PointerOps {
    type Value: ?Sized;
    type Pointer;

    unsafe fn from_raw(&self, value: * const Self::Value) -> Self::Pointer;

    fn into_raw(&self, ptr: Self::Pointer) -> * const Self::Value;
}

/// The `PointerOps` type used by an `Adapter` generated by `intrusive_adapter!`.
pub struct DefaultPointerOps<Pointer>(PhantomData<Pointer>);

impl<Pointer> DefaultPointerOps<Pointer> {
    /// Constructs an instance of `DefaultPointerOps`.
    #[inline]
    pub const fn new() -> DefaultPointerOps<Pointer> {
        DefaultPointerOps(PhantomData)
    }
}

impl<Pointer> Clone for DefaultPointerOps<Pointer> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}

impl<Pointer> Copy for DefaultPointerOps<Pointer> {}

impl<Pointer> Default for DefaultPointerOps<Pointer> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}

impl<T: ?Sized> PointerOps for DefaultPointerOps<UnsafeRef<T>> {
    type Value = T;
    type Pointer = UnsafeRef<T>;

    #[inline]
    unsafe fn from_raw(&self, raw: *const T) -> UnsafeRef<T> {
        UnsafeRef::from_raw(raw as *mut T)
    }

    #[inline]
    fn into_raw(&self, ptr: UnsafeRef<T>) -> *const T {
        UnsafeRef::into_raw(ptr) as *const T
    }
}

pub struct RcPointerOps<T, A>
where
    A: Allocator<T>,
{
    _phantom: PhantomData<T>,
    alloc: Cell<Option<NonNull<A>>>,
}

impl<T, A: Allocator<T>> RcPointerOps<T, A> {
    pub fn new() -> Self {
        Self {
            _phantom: PhantomData,
            alloc: Cell::new(None),
        }
    }

    pub fn is_valid(&self) -> bool {
        self.alloc.get().is_some()
    }
}

impl<T, A: Allocator<T>> Default for RcPointerOps<T, A> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}

impl<T, A: Allocator<T>> PointerOps for RcPointerOps<T, A> {
    type Value = T;
    type Pointer = Rc<T, A>;

    #[inline]
    unsafe fn from_raw(&self, raw: *const T) -> Rc<T, A> {
        // TODO: find a way to remove this check
        if self.alloc.get().is_none() {
            panic!("empty alloc in RcPointerOps");
        }
        Rc::<T, A>::from_raw_in(raw as *mut T, self.alloc.get().take().unwrap().as_mut())
    }

    #[inline]
    fn into_raw(&self, ptr: Rc<T, A>) -> *const T {
        let (raw, alloc) = Self::Pointer::into_raw_with_allocator(ptr);

        unsafe {
            self.alloc.set(Some(NonNull::new_unchecked(alloc)));
        }

        raw
    }
}

#[inline]
pub(crate) unsafe fn clone_pointer_from_raw<T: PointerOps>(
    pointer_ops: &T,
    ptr: *const T::Value,
) -> T::Pointer
where
    T::Pointer: Clone,
{
    /// Guard which converts an pointer back into its raw version
    /// when it gets dropped. This makes sure we also perform a full
    /// `from_raw` and `into_raw` round trip - even in the case of panics.
    struct PointerGuard<'a, T: PointerOps> {
        pointer: ManuallyDrop<T::Pointer>,
        pointer_ops: &'a T,
    }

    impl<'a, T: PointerOps> Drop for PointerGuard<'a, T> {
        #[inline]
        fn drop(&mut self) {
            // Prevent shared pointers from being released by converting them
            // back into the raw pointers
            // SAFETY: `pointer` is never dropped. `ManuallyDrop::take` is not stable until 1.42.0.
            let _ = self
                .pointer_ops
                .into_raw(unsafe { core::ptr::read(&*self.pointer) });
        }
    }

    let holder = PointerGuard {
        pointer: ManuallyDrop::new(pointer_ops.from_raw(ptr)),
        pointer_ops,
    };
    holder.pointer.deref().clone()
}

