[package]
name = "matter"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
opt-level = 0
debug = true
lto = false
panic = "abort"

[features]
default = []
panic_handler = []
chip_config_error_source = []
