pub const CHIP_SYSTEM_CONFIG_PACKETBUFFER_CAPACITY_MAX: u32 = 256;
pub const CHIP_SYSTEM_CONFIG_PACKETBUFFER_POOL_SIZE: u32 = 15;
pub const CHIP_SYSTEM_CONFIG_HEADER_RESERVE_SIZE: u32 = 26+12;
pub const CHIP_SYSTEM_CONFIG_MAX_LARGE_BUFFER_SIZE_BYTES: u32 = 2048;
